title: Eliton Nachbar # your name (or website title) here
logo: "/images/perfil.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  ğŸŒ± Estudando: Machine learning e EstatÃ­stica; 
  âœğŸ» Cursando: Bacharelado em CiÃªncia de Dados pela Univesp;
  ğŸ‘¨â€ğŸ“ Graduado em AdministraÃ§Ã£o pela Unip em 2014.
  <br></br>
  3+ Projetos em CiÃªncia de Dados usando AnÃ¡lise ExploratÃ³ria (EDA), Python e as principais
     bibliotecas como Pandas, Plotly, Seaborn, Matplotlib e Numpy. Os projetos podem ser vistos ao lado â¡ï¸ 
  <br><br>
  Conhecimento em SQL e SQLite, usando Dbeaver.
  <br><br>
  Conhecimento em PowerBI, Dax e Power Query.</br>
  <br><br>
  <a href="https://www.linkedin.com/in/elitonnachbar/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'

