title: Eliton Nachbar # your name (or website title) here
logo: "/images/perfil.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  ðŸŒ± Estudando: Machine learning e EstatÃ­stica;
  âœðŸ» Cursando: Bacharelado em CiÃªncia de Dados pela Univesp;
  ðŸ‘¨â€ðŸŽ“ Graduado em AdministraÃ§Ã£o pela Unip em 2014.
  3+ Projetos em CiÃªncia de Dados usando AnÃ¡lise ExploratÃ³ria (EDA), Python e as principais
  bibliotecas como Pandas, Plotly, Seaborn, Matplotlib e Numpy. Os projetos podem ser vistos ao lado -->
  Conhecimento em SQL e SQLite, usando Dbeaver.
  Conhecimento em PowerBI, Dax e Power Query.
  <br><br><i>
  ðŸŒ± Studiyng: Machine learning and Statistic;
  âœðŸ» Coursing: Bacharel in Data Science At Univesp;
  ðŸ‘¨â€ðŸŽ“ Graduated in Business at Unip in 2014.
  3+ Projects in Data Science using EDA, Python and the main libraries like
  Pandas, Plotly, Seaborn, Matplotlib and Numpy. The projects are specified beside -->
  Experience in SQL and SQLite, using Dbeaver.
  Experience in PowerBI, Dax and Power Query.</i>
   <br><br>
  <a href="https://www.linkedin.com/in/elitonnachbar/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'

