title: Eliton Nachbar # your name (or website title) here
logo: "/images/perfil.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  ğŸŒ± Estudando: Machine learning e EstatÃ­stica; 
  <li> âœğŸ» Cursando: Bacharelado em CiÃªncia de Dados pela Univesp;</li>
  <li> ğŸ‘¨â€ğŸ“ Graduado em AdministraÃ§Ã£o pela Unip em 2014.</li>
 <li>3+ Projetos em CiÃªncia de Dados usando AnÃ¡lise ExploratÃ³ria (EDA), Python e as principais</br>
     bibliotecas como Pandas, Plotly, Seaborn, Matplotlib e Numpy. Os projetos podem ser vistos ao lado --></li>
  <li>Conhecimento em SQL e SQLite, usando Dbeaver.</li>
  <li>Conhecimento em PowerBI, Dax e Power Query.</li></br>
  
  <a href="https://www.linkedin.com/in/elitonnachbar/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'

